export const NUMBER_OF_VISABLE_IMAGES = 5;

export const FETCH_IMAGES_STARTED = 'FETCH_IMAGES_STARTED';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FALIURE = 'FETCH_IMAGES_FALIURE';
export const PREV_IMAGE = 'PREV_IMAGE';
export const NEXT_IMAGE = 'NEXT_IMAGE';